# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '模块一' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 模块一

pod 'AFNetworking', '~> 3.0'

  target '模块一Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '模块一UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
